networks:
  default:
    name: tg_network

services:

  client:
    container_name: tg_client
    build: ./client
    command: npm run dev
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    expose:
      - "8080"
    environment:
      - NODE_ENV=development
      - TLS_PORT=${HOST_PORT}

  api:
    container_name: tg_api
    build: ./api
    command: npm run dev
    depends_on:
      - postgresql
    volumes:
      - ./api/src:/app/src
    expose:
      - "3000"
    env_file:
      - ./api/.env
    environment:
      - ADDRESS=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000

  postgresql:
    container_name: tg_postgresql
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=talentgraph
      - POSTGRES_PASSWORD=talentgraph
      - POSTGRES_DB=talentgraph

  caddy:
    container_name: tg_caddy
    image: caddy:latest
    ports:
      - "${HOST_PORT}:80"
      - "${HOST_PORT_SSL}:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client
      - api

    # adminer:
    #   container_name: tg_adminer
    #   image: adminer:5.4.2
    #   ports:
    #     - "8081:8080" # Access directly via http://localhost:8081
    #   depends_on:
    #     - postgresql


volumes:
  db_data:
  caddy_data:
  caddy_config: