<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const isLoading = ref<boolean>(false)
const userError = ref<string | null>(null)

// PopUp Listener to catch the message sent by your backend callback
const handleLinkedInAuthMessage = (event: MessageEvent) => {
  // Ensure the origin matches your local development environment setup
  if (event.origin !== "https://talentgraph.localhost:8443") return

  if (event.data.status === 'success') {
    if (event.data.token) {
      // Save your platform's session token generated by your backend
      localStorage.setItem('tg_recruiter_token', event.data.token)
    }
    // Redirect cleanly to the recruiter dashboard workspace
    router.push('/dashboard/recruiter')
  } else if (event.data.status === 'error') {
    userError.value = event.data.message || 'LinkedIn authentication failed.'
    isLoading.value = false
  }
}

onMounted(() => {
  window.addEventListener('message', handleLinkedInAuthMessage)
})

onUnmounted(() => {
  window.removeEventListener('message', handleLinkedInAuthMessage)
})

const handleLinkedInOAuth = () => {
  isLoading.value = true
  userError.value = null

  // Replace this placeholder with your actual LinkedIn Developer Client ID
  const LINKEDIN_CLIENT_ID = "YOUR_LINKEDIN_CLIENT_ID"
  
  // Your Fastify backend endpoint that accepts the LinkedIn code, exchanges it, and posts the message back
  const REDIRECT_URI = encodeURIComponent("https://talentgraph.localhost:8443/api/auth/linkedin/callback")
  
  // Standard LinkedIn OpenID Connect scopes for retrieving name and email profiles safely
  const SCOPE = encodeURIComponent("openid profile email")
  
  // Randomized string to protect against CSRF attacks
  const STATE = "RANDOM_SECURITY_STATE_STRING"

  const LINKEDIN_URL = `https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=${LINKEDIN_CLIENT_ID}&redirect_uri=${REDIRECT_URI}&state=${STATE}&scope=${SCOPE}`

  // Calculate centered coordinates for the secondary popup window
  const width = 600, height = 600
  const left = (window.innerWidth / 2) - (width / 2)
  const top = (window.innerHeight / 2) - (height / 2)

  try {
    window.open(
      LINKEDIN_URL,
      "LinkedIn Auth",
      `width=${width},height=${height},top=${top},left=${left}`
    )
  } catch (error) {
    console.error('Error opening LinkedIn OAuth popup:', error)
    userError.value = 'Failed to open authentication window.'
    isLoading.value = false
  }
}
</script>

<template>
  <main class="shell">
    <section class="auth-box">
      <p class="eyebrow">TalentGraph / Recruiter Gateway</p>
      <h1>Recruiter Verification</h1>
      <p class="body-text">
        Connect your corporate corporate identity via LinkedIn to gain access to candidate matchmaking tools.
      </p>
      
      <p v-if="userError" class="body-text" style="color: #ef4444; margin-bottom: 16px;">
        {{ userError }}
      </p>

      <button 
        @click="handleLinkedInOAuth" 
        :disabled="isLoading" 
        class="black-button"
      >
        {{ isLoading ? 'Awaiting Verification...' : 'Verify with LinkedIn' }}
      </button>
    </section>
  </main>
</template>